-- Autorización opaca, temporal y de un solo uso para que un GERENTE o ADMINISTRADOR
-- reautorice un descuento manual excepcional por línea de producto (T6). Solo se
-- persiste el hash del token entregado al cliente; el token en claro nunca se guarda.

CREATE TABLE autorizaciones_descuento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    autorizador_usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    vendedor_usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    tienda_id BIGINT NOT NULL REFERENCES tiendas(id),
    producto_id BIGINT NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    porcentaje NUMERIC(5, 2) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    carrito_id VARCHAR(100) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL DEFAULT now(),
    fecha_expiracion TIMESTAMP NOT NULL,
    consumida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_consumo TIMESTAMP,

    CONSTRAINT chk_autorizacion_descuento_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_autorizacion_descuento_porcentaje CHECK (porcentaje >= 0 AND porcentaje <= 30),
    CONSTRAINT chk_autorizacion_descuento_vigencia CHECK (fecha_expiracion > fecha_emision),
    CONSTRAINT chk_autorizacion_descuento_consumo CHECK (
        (consumida = FALSE AND fecha_consumo IS NULL) OR
        (consumida = TRUE AND fecha_consumo IS NOT NULL)
    )
);

CREATE INDEX idx_autorizaciones_descuento_carrito_id ON autorizaciones_descuento(carrito_id);
CREATE INDEX idx_autorizaciones_descuento_vendedor_id ON autorizaciones_descuento(vendedor_usuario_id);

-- Referencia de auditoría desde el detalle de venta hacia la autorización que
-- efectivamente se consumió para esa línea. Coherente con tipo_descuento: una línea
-- MANUAL siempre tiene una, ninguna otra la tiene (no se toca el CHECK de V9, que ya
-- exige NINGUNO/MANUAL sin promoción automática asociada).
ALTER TABLE detalles_venta
    ADD COLUMN autorizacion_descuento_id BIGINT REFERENCES autorizaciones_descuento(id);

ALTER TABLE detalles_venta
    ADD CONSTRAINT chk_detalle_autorizacion_manual CHECK (
        (tipo_descuento = 'MANUAL' AND autorizacion_descuento_id IS NOT NULL) OR
        (tipo_descuento <> 'MANUAL' AND autorizacion_descuento_id IS NULL)
    );

CREATE INDEX idx_detalles_venta_autorizacion_descuento_id ON detalles_venta(autorizacion_descuento_id);
