-- Modelo de promociones automáticas de producto/categoría. Primera regla soportada:
-- descuento por cantidad. El diseño permite agregar tipos futuros (DOS_POR_UNO,
-- PRECIO_ESPECIAL, PORCENTAJE_TEMPORAL) como nuevas tablas de regla dedicadas, sin
-- almacenar código ejecutable ni expresiones arbitrarias.

CREATE TABLE promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    tipo VARCHAR(30) NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    producto_id BIGINT REFERENCES productos(id),
    categoria_id BIGINT REFERENCES categorias(id),
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    prioridad INTEGER NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT chk_promocion_alcance_xor CHECK (
        (producto_id IS NOT NULL AND categoria_id IS NULL) OR
        (producto_id IS NULL AND categoria_id IS NOT NULL)
    ),
    CONSTRAINT chk_promocion_vigencia CHECK (
        fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_fin > fecha_inicio
    ),
    CONSTRAINT chk_promocion_prioridad CHECK (prioridad >= 0)
);

CREATE INDEX idx_promociones_producto_id ON promociones(producto_id);
CREATE INDEX idx_promociones_categoria_id ON promociones(categoria_id);
CREATE INDEX idx_promociones_activa ON promociones(activa);

CREATE TABLE reglas_descuento_cantidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promocion_id BIGINT NOT NULL UNIQUE REFERENCES promociones(id) ON DELETE CASCADE,
    cantidad_minima INTEGER NOT NULL,
    porcentaje NUMERIC(5, 2) NOT NULL,

    CONSTRAINT chk_regla_cantidad_minima CHECK (cantidad_minima > 0),
    CONSTRAINT chk_regla_cantidad_porcentaje CHECK (porcentaje > 0 AND porcentaje < 100)
);
