spring:
  datasource:
    url: jdbc:h2:mem:posdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true # Para que puedas ver la DB en /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password