spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/posdb_dev}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:posuser}
    password: ${DATABASE_PASSWORD:pospass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    user:
      name: user
      password: password

app:
  jwt:
    secret: ${JWT_SECRET:Ptt-k@uuaii-JWT-S3cr3t-K3y-256-b1ts-M1n1mum!}
